spring:
  application:
    name: cqrs_premium

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:premiumdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis Configuration
  redis:
    host: localhost
    port: 6379

  # Redis Repository Configuration
  data:
    redis:
      repositories:
        enabled: true

  # Cache Configuration
  cache:
    type: redis

  # Web MVC Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Logging Configuration
logging:
  level:
    root: INFO
    org:
      springframework:
        data: DEBUG
        data.convert.CustomConversions: INFO
    com:
      sy:
        cafe: DEBUG

# Server Configuration
server:
  port: 8080

# Custom Distributed Lock Configuration
distribute:
  lock:
    enable: true

# Actuator Configuration (if needed)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Kafka Configuration (commented out, uncomment if needed)
# kafka:
#   bootstrap-servers: localhost:9093
#   producer:
#     key-serializer: org.apache.kafka.common.serialization.StringSerializer
#     value-serializer: org.apache.kafka.common.serialization.StringSerializer